### PR TITLE
Prevent orphans in paged media

### PR DESCRIPTION
**Pull request by jornmineur**
Twila mentioned that she needs to tweak PDFs in order to prevent orphans; a simple line of CSS can at least keep 3 lines together which should look better in any case

### CODE REVIEW

**Comment by Jed-Lehmann** [comment]
@jornmineur Yes, this sounds good. Beforre merging, I just wanted to double check you looked at the PDF output to make sure it doesn't introduce any issues with marginalia? I ask because you've applied the rule to the body, which might affect all text.

**Comment by jornmineur** [comment]
> @jornmineur Yes, this sounds good. Beforre merging, I just wanted to double check you looked at the PDF output to make sure it doesn't introduce any issues with marginalia? I ask because you've applied the rule to the body, which might affect all text.

I tested it by creating a PDF from the browser, which is not entirely the same thing as processing with Docraptor of course. But I can't figure out how to let Docraptor do the processing. Through the browser it worked fine.

@Jed-Lehmann

**Comment by Jed-Lehmann** [comment]
It definitely needs to be tested with Docraptor, as it's rendering engine is very different from the browser. 

Docs for generating a PDF to the root folder with Docraptor are here: https://www.notion.so/eaccent/Converting-to-PDF-format-9d1177c283314ac683cb5faa45740829

@jornmineur

**Comment by Jed-Lehmann** [comment]
@jornmineur Are you still working on this one?

**Comment by jornmineur** [comment]
I have second thoughts about this fix, I think applying the CSS to the body element is too high-level and I don't have enough context to assign it to the right selectors. I'll close this PR.

**Pull request closed without merging**
